// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axpejcjzsedbyygqpbxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cGVqY2p6c2VkYnl5Z3FwYnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzY1MTUsImV4cCI6MjA3MDE1MjUxNX0.fEYjcciPlhZkSptKG5lo83WH-ydC9CkPyOznV6cO_us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});